### ISSUE TITLE
better stacktraces

### ISSUE THREAD

**Issue by jantimon** [credred/karma-vite#1]
hey :)

would it be possible to improve the stack traces?

right now it is hard to find out which files are involved in an error:

```
    at renderWithHooks (http://localhost:9876/node_modules/.vite/deps/chunk-Q2K3H3PB.js?v=7bef19f7:11191:26)
    at mountIndeterminateComponent (http://localhost:9876/node_modules/.vite/deps/chunk-Q2K3H3PB.js?v=7bef19f7:13353:21)
    at beginWork (http://localhost:9876/node_modules/.vite/deps/chunk-Q2K3H3PB.js?v=7bef19f7:14161:22)
    at HTMLUnknownElement.callCallback2 (http://localhost:9876/node_modules/.vite/deps/chunk-Q2K3H3PB.js?v=7bef19f7:3795:22)
    at Object.invokeGuardedCallbackDev (http://localhost:9876/node_modules/.vite/deps/chunk-Q2K3H3PB.js?v=7bef19f7:3820:24)
    at invokeGuardedCallback (http://localhost:9876/node_modules/.vite/deps/chunk-Q2K3H3PB.js?v=7bef19f7:3854:39)
     ReferenceError: global is not defined
 at resetIntersectionMocking (http://localhost:9876/node_modules/.vite/deps/react-intersection-observer_test-utils.js?v=7bef19f7:75:7)
    at UserContext.<anonymous> (http://localhost:9876/node_modules/.vite/deps/react-intersection-observer_test-utils.js?v=7bef19f7:27:9)
    at <Jasmine>
```

**Comment by credred** [comment]
hi, do you want to hide the url origin in the stack trace, such as the following?
```
    at renderWithHooks (node_modules/.vite/deps/chunk-Q2K3H3PB.js:11191:26)
    at mountIndeterminateComponent (node_modules/.vite/deps/chunk-Q2K3H3PB.js:13353:21)
    at beginWork (node_modules/.vite/deps/chunk-Q2K3H3PB.js:14161:22)
    at HTMLUnknownElement.callCallback2 (node_modules/.vite/deps/chunk-Q2K3H3PB.js:3795:22)
    at Object.invokeGuardedCallbackDev (node_modules/.vite/deps/chunk-Q2K3H3PB.js:3820:24)
    at invokeGuardedCallback (node_modules/.vite/deps/chunk-Q2K3H3PB.js:3854:39)
     ReferenceError: global is not defined
 at resetIntersectionMocking (node_modules/.vite/deps/react-intersection-observer_test-utils.js:75:7)
    at UserContext.<anonymous> (node_modules/.vite/deps/react-intersection-observer_test-utils.js:27:9)
    at <Jasmine>
```
In this way, the editor can locate specific files.

I can integrate a karma reporter to implement it according to the karma-sepc-reporter.

Finally, I recommend you use the browser to debug errors, because sometimes vite uses the virtual file function. Therefore, only browsers have complete data

**Comment by jantimon** [comment]
yes that's already way better 👍
